x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:

  geoipupdate:
    image: maxmindinc/geoipupdate:latest
    restart: always
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: GeoLite2-City
      GEOIPUPDATE_FREQUENCY: 72
    volumes:
      - geoip:/usr/share/GeoIP
    networks:
      - url_shortener_network
    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/share/GeoIP/GeoLite2-City.mmdb"]
      interval: 10s
      timeout: 3s
      retries: 30
    logging: *default-logging

  frontend:
    image: pratul74/url-shortener-frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - url_shortener_network
    logging: *default-logging
    pull_policy: always

  api:
    image: pratul74/url-shortener-backend:latest

    restart: always

    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=8000

    env_file:
      - .env

    volumes:
      - geoip:/usr/share/GeoIP:ro
    networks:
      - url_shortener_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

    logging: *default-logging

    pull_policy: always

    depends_on:
      geoipupdate:
        condition: service_healthy

  analytics_worker:
    image: pratul74/url-shortener-backend:latest

    restart: always

    command:
      - python
      - -m
      - analytics.bootstrap

    env_file:
      - .env

    volumes:
      - geoip:/usr/share/GeoIP:ro
    networks:
      - url_shortener_network

    logging: *default-logging

    pull_policy: always

    depends_on:
      geoipupdate:
        condition: service_healthy


networks:
  url_shortener_network:
    name: url_shortener_network

volumes:
  geoip:
