"""Replace click_events with analytics

Revision ID: f057fa72f29a
Revises: 554377c688d3
Create Date: 2026-09-27 22:51:45.393404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f057fa72f29a'
down_revision: Union[str, Sequence[str], None] = '554377c688d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('total_clicks', sa.BigInteger(), nullable=False),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('browsers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('devices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('os', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('referrer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url_id')
    )
    op.create_index(op.f('ix_analytics_url_id'), 'analytics', ['url_id'], unique=True)
    op.drop_index(op.f('ix_click_events_clicked_at'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_url_id'), table_name='click_events')
    op.drop_table('click_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clicked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('referrer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], name=op.f('click_events_url_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('click_events_pkey'))
    )
    op.create_index(op.f('ix_click_events_url_id'), 'click_events', ['url_id'], unique=False)
    op.create_index(op.f('ix_click_events_clicked_at'), 'click_events', ['clicked_at'], unique=False)
    op.drop_index(op.f('ix_analytics_url_id'), table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
